theme: jekyll-theme-leap-day
title: [Replication Package for “Generating Query-specific Class API Summaries” (ESEC/FSE 2019)]
description: ["Mingwei Liu, Xin Peng, Andrian Marcus, Zhenchang Xing, Wenkai Xie, Shuangshuang Xing, and Yang Liu"]
show_downloads: false
is_user_page: false
github.is_user_page: false
