theme: jekyll-theme-cayman
title: [Replication Package for “Generating Query-specific Class API Summaries” (ESEC/FSE 2019)]
description: ["Mingwei Liu, Xin Peng, Andrian Marcus, Zhenchang Xing, Wenkai Xie, Shuangshuang Xing, and Yang Liu"]
